# Generated by Django 3.1 on 2021-05-18 08:29

import Summarize.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSummarizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioFile', models.FileField(upload_to=Summarize.models.uniqueFileName)),
                ('isSummarized', models.BooleanField(default=False)),
                ('isRecognized', models.BooleanField(default=False)),
                ('isMailSent', models.BooleanField(default=False)),
                ('recognizedText', models.TextField(default='')),
                ('summarizedText', models.TextField(default='')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AudioSummarizeModel',
            },
        ),
    ]
